name: SAP BTP deployment with cTMS
on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org
          cache: npm
      - run: npm ci --ignore-scripts
      - run: npm run build --if-present
      - uses: https://github.com/mauriciolauffer/ctms@main
        with:
          TOKEN_SERVICE_URL: ${{ secrets.TOKEN_SERVICE_URL }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          CTMS_URL: ${{ secrets.CTMS_URL }}
          CTMS_NODE_NAME: ${{ secrets.CTMS_NODE_NAME }}
          USER_NAME: ${{ secrets.USER_NAME }}
          FILE_PATH: ${{ secrets.FILE_PATH }}
